import { NextRequest, NextResponse } from "next/server";
import { requireUser, isAdminRole } from "@/lib/session";
import { getAdminSalarySlip, getMySalarySlip } from "@/services/payroll.service";
import { hasPermission } from "@/lib/permissions";
import type { Role } from "@/lib/permissions";

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

function money(n: number) {
  return Number(n).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await requireUser();
  const { id } = await params;

  const canManage =
    isAdminRole(user.role) ||
    hasPermission(user.role as Role, "payroll:manage");

  const slip = canManage
    ? await getAdminSalarySlip(user.companyId!, user.role, id)
    : await getMySalarySlip(user.companyId!, user.id, user.role, id);

  const period = `${MONTHS[slip.month - 1]} ${slip.year}`;
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payslip · ${period} · ${slip.employee.firstName} ${slip.employee.lastName}</title>
  <style>
    body { font-family: Georgia, "Times New Roman", serif; color: #111; margin: 0; padding: 32px; background: #f7f5f0; }
    .sheet { max-width: 720px; margin: 0 auto; background: #fff; border: 2px solid #111; padding: 28px 32px; }
    h1 { margin: 0; font-size: 22px; letter-spacing: -0.02em; }
    .muted { color: #555; font-size: 13px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px 24px; margin-top: 20px; font-size: 14px; }
    .row { display: flex; justify-content: space-between; border-bottom: 1px solid #ddd; padding: 6px 0; }
    .net { margin-top: 20px; font-size: 22px; font-weight: 800; border-top: 2px solid #111; padding-top: 12px; }
    .actions { max-width: 720px; margin: 16px auto; display: flex; gap: 8px; }
    button, a.btn { font-family: inherit; background: #111; color: #fff; border: 0; padding: 10px 16px; cursor: pointer; text-decoration: none; font-size: 13px; }
    @media print {
      body { background: #fff; padding: 0; }
      .actions { display: none; }
      .sheet { border: none; max-width: none; }
    }
  </style>
</head>
<body>
  <div class="actions">
    <button onclick="window.print()">Print / Save PDF</button>
    <a class="btn" href="javascript:history.back()">Back</a>
  </div>
  <div class="sheet">
    <h1>${escapeHtml(slip.company.name)}</h1>
    <p class="muted">Salary slip · ${period} · Status: ${escapeHtml(slip.status)}</p>
    <div class="grid">
      <div><strong>Employee</strong><br/>${escapeHtml(slip.employee.firstName)} ${escapeHtml(slip.employee.lastName)}</div>
      <div><strong>Code</strong><br/>${escapeHtml(slip.employee.employeeCode)}</div>
      <div><strong>Working days</strong><br/>${slip.workingDays}</div>
      <div><strong>Present days</strong><br/>${slip.presentDays}</div>
      <div><strong>LOP days</strong><br/>${slip.lopDays}</div>
      <div><strong>OT hours</strong><br/>${slip.overtimeHours}</div>
    </div>
    <div style="margin-top:24px">
      <div class="row"><span>Basic</span><span>₹ ${money(slip.basic)}</span></div>
      <div class="row"><span>Allowances</span><span>₹ ${money(slip.allowances)}</span></div>
      <div class="row"><span>PF</span><span>₹ ${money(slip.pf)}</span></div>
      <div class="row"><span>ESI</span><span>₹ ${money(slip.esi)}</span></div>
      <div class="row"><span>TDS</span><span>₹ ${money(slip.tds)}</span></div>
      <div class="row"><span>Other deductions</span><span>₹ ${money(slip.deductions)}</span></div>
    </div>
    <div class="net">Net pay: ₹ ${money(slip.netPay)}</div>
    ${slip.notes ? `<p class="muted" style="margin-top:16px">Notes: ${escapeHtml(slip.notes)}</p>` : ""}
    <p class="muted" style="margin-top:28px">Generated by WorkPilot · ${new Date().toLocaleDateString("en-IN")}</p>
  </div>
  <script>window.addEventListener("load", () => { /* ready for print */ });</script>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
